version: '4'

services:
  mongo-card-creator:
    image: mongo:5
    container_name: technical_interview_angie
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: boxful
    volumes:
      - ./db/orders:/data/db
      - ./db/init-scripts:/docker-entrypoint-initdb.d